# Site settings
title: Vikesh Tiwari
email: tvicky002@gmail.com
url: https://vicky002.github.io
description: " About Vikesh Tiwari"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Vikesh Tiwari

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/vikesh002
  - title: linkedin
    url: https://www.linkedin.com/in/vikeshtiwari/
  - title: stack-overflow
    url: http://stackoverflow.com/users/4115244/blackhat002
  - title: github
    url: https://github.com/vicky002

# Build settings
markdown: kramdown
permalink: pretty
