# Dependencies
markdown: kramdown
kramdown:
  input: GFM


# Setup
title: Vikesh Tiwari
SEOTitle: Vikesh Tiwari Blog | vicky002
header-img: img/home-bg.jpg
email: hi@eulercoder.me
description: 'Vikesh Tiwari - also known as vicky002 in this online virtual world, currently a third year undergrad at SPIT, Mumbai. Loves to travel and talk to random people.'
baseurl:     ''
keyword: "vicky002, vikesh tiwari, @vikesh002, vicky, blackhat002, vikesh tiwari codechef, vicky tiwari, vikesh tiwari github"
url:         'http://eulercoder.me'

# Social icons
RSS: false
show_social_icons: true
github_username: vicky002
twitter_username: vikesh002
linkedin_username: vikeshtiwari
facebook_username: blackhat002

# Analytics setting
ga_track_id: 'UA-45497633-11'
ga_domain: vicky002.github.io
disqus_username: vicky002


# Gems
gems: [jekyll-paginate]


# Build setting
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# Sidebar setting
sidebar: true
sidebar-about-description: "Vikesh Tiwari - also known as vicky002 in this online virtual world, currently a third year undergrad at SPIT, Mumbai. Loves to travel and talk to random people."
sidebar-avatar: /img/avatar-vicky.jpg

# featured tags
featured-tags: true
featured-condition-size: 1

# friends

friends: [
  {
    "title": "Krish Munot",
    "href": "https://krishmunot.github.io"
  },
  {
    "title": "Pratik Solim",
    "href": "http://pratiksolim.xyz"
  },
  {
    "title": "Shivam Khandelwal",
    "href": "http://shivamkhandelwal.in"
  }
]

